"""
@file
@ingroup hellomalif2
@copyright ESO - European Southern Observatory

@defgroup hellomalif2
@ingroup hellomalif2
@brief hellomalif2 CII/MAL interface module.
"""

from wtools.module import declare_malicd

declare_malicd(use=['externalif2'])
