/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      orthogonal
 * 
 */


 

#ifndef BLINKYCHOICE_ORTHOGONAL_STATES_H_
#define BLINKYCHOICE_ORTHOGONAL_STATES_H_

/**
 * Enumerate all the states that the state machine may be in at any given time.
 * An addition to the Samek pattern, state enums facilitate convenient
 * query of current state a State Machine is in at a given moment.
 */
typedef enum blinkyChoice_orthogonal_state {
    BLINKYCHOICE_ORTHOGONAL__TOP__, /* Top = 0 */
    BLINKYCHOICE_ORTHOGONAL_INIT,
    BLINKYCHOICE_ORTHOGONAL_ORTHOGONALSTATE,
    BLINKYCHOICE_ORTHOGONAL_ORTHOGONALSTATE_REGION1_FINALSTATE0,
    BLINKYCHOICE_ORTHOGONAL_ORTHOGONALSTATE_REGION1_STATE1,
    BLINKYCHOICE_ORTHOGONAL_ORTHOGONALSTATE_REGION2_FINALSTATE1,
    BLINKYCHOICE_ORTHOGONAL_ORTHOGONALSTATE_REGION2_STATE2,

} blinkyChoice_orthogonal_state;

#endif /* BLINKYCHOICE_ORTHOGONAL_STATES_H_ */
