/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      historySM
 * 
 *
 * ############### Requirements ###############
 *  Implements: 
 * - https://cae-jama.jpl.nasa.gov/rest/latest/items/724776 
 * - https://cae-jama.jpl.nasa.gov/rest/latest/items/724777 
 *
 * ############################################
 *
 */


 
#include <stdio.h>
#include <string.h>
#include <log_event.h>
#include <assert.h>
#include <blinkyChoice_historySM.h>
#include <blinkyChoice_historySM_impl.h>





/**
 * blinkyChoice_historySM Constructor
 */
blinkyChoice_historySM *blinkyChoice_historySM_constructor (blinkyChoice_historySM *me, const char *objNameNew, blinkyChoice_historySM_impl *implObj, QActive *active) {
    QActive_ctor((QActive *)me, (QStateHandler )&blinkyChoice_historySM_initial);
    strncpy(me->objName, objNameNew, 128);
    strncat(me->objName, ":blinkyChoice_historySM", 128-strlen(me->objName));
    me->impl = implObj;
    if (0 == active) {  // self IS the active object
        me->active = (QActive *)me;
    } else {  // set containing machine as active object
        me->active = active;
    }
    blinkyChoice_historySM_impl_set_qactive(me->impl, me->active);  // give impl access to parent QActive

    // Timer events initialized here
    QTimeEvt_ctor(&(me->onRelativeTimer), ON_TIMER_SIG);

    // State is initially at TOP
    me->myState = BLINKYCHOICE_HISTORYSM__TOP__;

    return me;
}

blinkyChoice_historySM_impl *blinkyChoice_historySM_get_impl (blinkyChoice_historySM *me) {
    return me->impl;
}

blinkyChoice_historySM_state blinkyChoice_historySM_get_current_state (blinkyChoice_historySM *me) {
    return me->myState;
}

/**
 * initial state definition
 */
QState blinkyChoice_historySM_initial (blinkyChoice_historySM *me, QEvt const *e) {
    // Subscribe to all the signals to which this state machine needs to respond.
	if (me->active == (QActive *)me) {
		QActive_subscribe(me->active, BLINKYCHOICE_TURN_OFF_SIG);
		QActive_subscribe(me->active, BLINKYCHOICE_TURN_ON_SIG);
		QActive_subscribe(me->active, BLINKYCHOICE_WIF_HEY_SIG);
		QActive_subscribe(me->active, _SIG_BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_COMPLETE_);
	}

    return Q_TRAN(&blinkyChoice_historySM_initState);
}

/**
 * backup state definition
 */
QState blinkyChoice_historySM_backup (blinkyChoice_historySM *me, QEvt const *e) {
    switch (e->sig) {
        case Q_ENTRY_SIG:
            me->myState = BLINKYCHOICE_HISTORYSM_BACKUP;
            return Q_HANDLED();

        case Q_EXIT_SIG:
            return Q_HANDLED();

        case BLINKYCHOICE_TURN_ON_SIG:
            return Q_TRAN(&blinkyChoice_historySM_composite_off);

        case BLINKYCHOICE_TURN_OFF_SIG:
            return Q_TRAN(me->compositeshallowHistory0);


    }
    return Q_SUPER(&QHsm_top);
}

/**
 * composite state definition
 */
QState blinkyChoice_historySM_composite (blinkyChoice_historySM *me, QEvt const *e) {
    switch (e->sig) {
        case Q_INIT_SIG:
            return Q_TRAN(&blinkyChoice_historySM_composite_on);

        case Q_ENTRY_SIG:
            me->myState = BLINKYCHOICE_HISTORYSM_COMPOSITE;
            return Q_HANDLED();

        case Q_EXIT_SIG:
            return Q_HANDLED();


    }
    return Q_SUPER(&QHsm_top);
}

/**
 * on state definition
 */
QState blinkyChoice_historySM_composite_on (blinkyChoice_historySM *me, QEvt const *e) {
    switch (e->sig) {
        case Q_ENTRY_SIG:
            me->myState = BLINKYCHOICE_HISTORYSM_COMPOSITE_ON;
            me->compositeshallowHistory0 = (QStateHandler)&blinkyChoice_historySM_composite_on;

            QTimeEvt_postIn(&(me->onRelativeTimer), me->active, 5s);
            return Q_HANDLED();

        case Q_EXIT_SIG:
            QTimeEvt_disarm(&(me->onRelativeTimer));
            return Q_HANDLED();

        case BLINKYCHOICE_WIF_HEY_SIG:
            return Q_TRAN(&blinkyChoice_historySM_backup);

        case ON_TIMER_SIG:
            return Q_TRAN(&blinkyChoice_historySM_composite_off);


    }
    return Q_SUPER(&blinkyChoice_historySM_composite);
}

/**
 * off state definition
 */
QState blinkyChoice_historySM_composite_off (blinkyChoice_historySM *me, QEvt const *e) {
    switch (e->sig) {
        case Q_INIT_SIG:
            return Q_TRAN(&blinkyChoice_historySM_composite_off_offInternaal);

        case Q_ENTRY_SIG:
            me->myState = BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF;
            me->compositeshallowHistory0 = (QStateHandler)&blinkyChoice_historySM_composite_off;

            return Q_HANDLED();

        case Q_EXIT_SIG:
            return Q_HANDLED();

        case BLINKYCHOICE_TURN_ON_SIG:
            return Q_TRAN(&blinkyChoice_historySM_composite_on);

        case BLINKYCHOICE_WIF_HEY_SIG:
            return Q_TRAN(&blinkyChoice_historySM_backup);


    }
    return Q_SUPER(&blinkyChoice_historySM_composite);
}

/**
 * subsubstate state definition
 */
QState blinkyChoice_historySM_composite_off_subsubstate (blinkyChoice_historySM *me, QEvt const *e) {
    switch (e->sig) {
        case Q_ENTRY_SIG:
            me->myState = BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_SUBSUBSTATE;
            return Q_HANDLED();

        case Q_EXIT_SIG:
            return Q_HANDLED();

        case BLINKYCHOICE_TURN_OFF_SIG:
            if (blinkyChoice_historySM_impl_hue(me->impl)){

                me->BLINKYCHOICE_HISTORYSM_COMPLETION_EVENT_.completion_evt.super.sig = _SIG_BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_COMPLETE_;
                me->BLINKYCHOICE_HISTORYSM_COMPLETION_EVENT_.completion_evt.substate = NULL;  // Comodo functionality not implemented
                QF_publish_(&(me->BLINKYCHOICE_HISTORYSM_COMPLETION_EVENT_.base_evt));
                return Q_TRAN(&blinkyChoice_historySM_composite_off_finalState0);
            }
            else {

                me->BLINKYCHOICE_HISTORYSM_COMPLETION_EVENT_.completion_evt.super.sig = _SIG_BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_COMPLETE_;
                me->BLINKYCHOICE_HISTORYSM_COMPLETION_EVENT_.completion_evt.substate = NULL;  // Comodo functionality not implemented
                QF_publish_(&(me->BLINKYCHOICE_HISTORYSM_COMPLETION_EVENT_.base_evt));
                return Q_TRAN(&blinkyChoice_historySM_composite_off_finalState0);
            }

            return Q_HANDLED();

        case BLINKYCHOICE_WIF_HEY_SIG:
            return Q_TRAN(&blinkyChoice_historySM_backup);


    }
    return Q_SUPER(&blinkyChoice_historySM_composite_off);
}

/**
 * offInternaal state definition
 */
QState blinkyChoice_historySM_composite_off_offInternaal (blinkyChoice_historySM *me, QEvt const *e) {
    switch (e->sig) {
        case Q_ENTRY_SIG:
            me->myState = BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_OFFINTERNAAL;
            return Q_HANDLED();

        case Q_EXIT_SIG:
            return Q_HANDLED();

        case BLINKYCHOICE_TURN_ON_SIG:
            return Q_TRAN(&blinkyChoice_historySM_composite_off_subsubstate);


    }
    return Q_SUPER(&blinkyChoice_historySM_composite_off);
}

/**
 * finalState0 state definition
 */
QState blinkyChoice_historySM_composite_off_finalState0 (blinkyChoice_historySM *me, QEvt const *e) {
    switch (e->sig) {
        case _SIG_BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_COMPLETE_:
            return Q_HANDLED();

        case Q_ENTRY_SIG:
            me->myState = BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_FINALSTATE0;
            return Q_HANDLED();

        case Q_EXIT_SIG:
            return Q_HANDLED();


    }
    return Q_SUPER(&blinkyChoice_historySM_composite_off);
}

/**
 * initState state definition
 */
QState blinkyChoice_historySM_initState (blinkyChoice_historySM *me, QEvt const *e) {
    switch (e->sig) {
        case Q_ENTRY_SIG:
            me->myState = BLINKYCHOICE_HISTORYSM_INITSTATE;
            return Q_HANDLED();

        case Q_EXIT_SIG:
            return Q_HANDLED();

        case BLINKYCHOICE_WIF_HEY_SIG:
            return Q_TRAN(&blinkyChoice_historySM_composite);


    }
    return Q_SUPER(&QHsm_top);
}
