/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      historySM
 * 
 */


 

#ifndef BLINKYCHOICE_HISTORYSM_STATES_H_
#define BLINKYCHOICE_HISTORYSM_STATES_H_

/**
 * Enumerate all the states that the state machine may be in at any given time.
 * An addition to the Samek pattern, state enums facilitate convenient
 * query of current state a State Machine is in at a given moment.
 */
typedef enum blinkyChoice_historySM_state {
    BLINKYCHOICE_HISTORYSM__TOP__, /* Top = 0 */
    BLINKYCHOICE_HISTORYSM_BACKUP,
    BLINKYCHOICE_HISTORYSM_COMPOSITE,
    BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF,
    BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_FINALSTATE0,
    BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_OFFINTERNAAL,
    BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_SUBSUBSTATE,
    BLINKYCHOICE_HISTORYSM_COMPOSITE_ON,
    BLINKYCHOICE_HISTORYSM_INITSTATE,

} blinkyChoice_historySM_state;

#endif /* BLINKYCHOICE_HISTORYSM_STATES_H_ */
