/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      absoluteTimerSM
 * 
 */


 

#ifndef BLINKYCHOICE_ABSOLUTETIMERSM_STATES_H_
#define BLINKYCHOICE_ABSOLUTETIMERSM_STATES_H_

/**
 * Enumerate all the states that the state machine may be in at any given time.
 * An addition to the Samek pattern, state enums facilitate convenient
 * query of current state a State Machine is in at a given moment.
 */
typedef enum blinkyChoice_AbsoluteTimerSM_state {
    BLINKYCHOICE_ABSOLUTETIMERSM__TOP__, /* Top = 0 */
    BLINKYCHOICE_ABSOLUTETIMERSM_ABSOLUTE_STATE2,
    BLINKYCHOICE_ABSOLUTETIMERSM_INITSTATE,

} blinkyChoice_AbsoluteTimerSM_state;

#endif /* BLINKYCHOICE_ABSOLUTETIMERSM_STATES_H_ */
