/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      historySM
 * 
 *
 * ############### Requirements ###############
 *  Implements: 
 * - https://<traceability-service-hostname>/724776 
 * - https://<traceability-service-hostname>/724777 
 *
 * ############################################
 *
 */


 

#ifndef BLINKYCHOICE_HISTORYSM_H_
#define BLINKYCHOICE_HISTORYSM_H_

#include <stdbool.h>
#include <qf_port.h>
#include <qassert.h>
#include <blinkyChoice_statechart_signals.h>
#include <blinkyChoice_historySM_states.h>
#include <blinkyChoice_historySM_impl.h>


/**
 * Declare the state machine struct, encapsulating the extended state variables.
 * It tracks any timers, owned orthogonal regions, history states, substates.
 */
typedef struct blinkyChoice_historySM {
    QActive super;  // C-style inheritance
    QActive *active;  // containing machine if this is a submachine instance
    char objName[128];
    blinkyChoice_historySM_impl *impl;
    enum blinkyChoice_historySM_state myState;

    /* Completion event for exiting from composite/orthogonal/submachine state */
    QCompletionEvt BLINKYCHOICE_HISTORYSM_COMPLETION_EVENT_;

    /* Bail event to terminate orthogonal/submachine substate */
    QEvt BLINKYCHOICE_HISTORYSM_BAIL_EVENT_;

    /* History state variables */
    QStateHandler compositeshallowHistory0;

    /* TimeEvents object instances (only relative timers are supported) */
    QTimeEvt onRelativeTimer;


} blinkyChoice_historySM;


/** 
 * blinkyChoice_historySM Constructor
 *
 * This State machine constructor is responsible for initializing
 * the object, allocating and initializing any orthogonal regions, 
 * and initializing the timers.
 */
blinkyChoice_historySM *blinkyChoice_historySM_constructor (blinkyChoice_historySM *me, const char *objNameNew, blinkyChoice_historySM_impl *implObj, QActive *active);

/**
  * Returns the instance of the Implementation class for this QActive.
  */
blinkyChoice_historySM_impl *blinkyChoice_historySM_get_impl (blinkyChoice_historySM *me);

/**
 * Returns the unique enum representing the current state of this machine.
 */
blinkyChoice_historySM_state blinkyChoice_historySM_get_current_state (blinkyChoice_historySM *me);

/**
 * Method to initialize state machine (equivalent to initial pseudostate)
 */
QState blinkyChoice_historySM_initial (blinkyChoice_historySM *me, QEvt const *e);

/**
 * State methods
 */
QState blinkyChoice_historySM_initState(blinkyChoice_historySM *me, QEvt const *e); 
QState blinkyChoice_historySM_composite(blinkyChoice_historySM *me, QEvt const *e); 
QState blinkyChoice_historySM_composite_on(blinkyChoice_historySM *me, QEvt const *e); 
QState blinkyChoice_historySM_composite_off(blinkyChoice_historySM *me, QEvt const *e); 
QState blinkyChoice_historySM_composite_off_subsubstate(blinkyChoice_historySM *me, QEvt const *e); 
QState blinkyChoice_historySM_composite_off_offInternaal(blinkyChoice_historySM *me, QEvt const *e); 
QState blinkyChoice_historySM_composite_off_finalState0(blinkyChoice_historySM *me, QEvt const *e); 
QState blinkyChoice_historySM_backup(blinkyChoice_historySM *me, QEvt const *e); 




#endif /* BLINKYCHOICE_HISTORYSM_H_ */
