/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      RelativeTimerSM
 * 
 *
 * ############### Requirements ###############
 *  Implements: 
 * - https://cae-jama.jpl.nasa.gov/rest/latest/items/724776 
 * - https://cae-jama.jpl.nasa.gov/rest/latest/items/724777 
 *
 * ############################################
 *
 */


 

#ifndef BLINKYCHOICE_RELATIVETIMERSM_H_
#define BLINKYCHOICE_RELATIVETIMERSM_H_

#include <stdbool.h>
#include <qf_port.h>
#include <qassert.h>
#include <blinkyChoice_statechart_signals.h>
#include <blinkyChoice_RelativeTimerSM_states.h>
#include <blinkyChoice_RelativeTimerSM_impl.h>


/**
 * Declare the state machine struct, encapsulating the extended state variables.
 * It tracks any timers, owned orthogonal regions, history states, substates.
 */
typedef struct blinkyChoice_RelativeTimerSM {
    QActive super;  // C-style inheritance
    QActive *active;  // containing machine if this is a submachine instance
    char objName[128];
    blinkyChoice_RelativeTimerSM_impl *impl;
    enum blinkyChoice_RelativeTimerSM_state myState;

    /* Completion event for exiting from composite/orthogonal/submachine state */
    QCompletionEvt BLINKYCHOICE_RELATIVETIMERSM_COMPLETION_EVENT_;

    /* Bail event to terminate orthogonal/submachine substate */
    QEvt BLINKYCHOICE_RELATIVETIMERSM_BAIL_EVENT_;

    /* TimeEvents object instances (only relative timers are supported) */
    QTimeEvt initStateRelativeTimer;


} blinkyChoice_RelativeTimerSM;


/** 
 * blinkyChoice_RelativeTimerSM Constructor
 *
 * This State machine constructor is responsible for initializing
 * the object, allocating and initializing any orthogonal regions, 
 * and initializing the timers.
 */
blinkyChoice_RelativeTimerSM *blinkyChoice_RelativeTimerSM_constructor (blinkyChoice_RelativeTimerSM *me, const char *objNameNew, blinkyChoice_RelativeTimerSM_impl *implObj, QActive *active);

/**
  * Returns the instance of the Implementation class for this QActive.
  */
blinkyChoice_RelativeTimerSM_impl *blinkyChoice_RelativeTimerSM_get_impl (blinkyChoice_RelativeTimerSM *me);

/**
 * Returns the unique enum representing the current state of this machine.
 */
blinkyChoice_RelativeTimerSM_state blinkyChoice_RelativeTimerSM_get_current_state (blinkyChoice_RelativeTimerSM *me);

/**
 * Method to initialize state machine (equivalent to initial pseudostate)
 */
QState blinkyChoice_RelativeTimerSM_initial (blinkyChoice_RelativeTimerSM *me, QEvt const *e);

/**
 * State methods
 */
QState blinkyChoice_RelativeTimerSM_initState(blinkyChoice_RelativeTimerSM *me, QEvt const *e); 
QState blinkyChoice_RelativeTimerSM_Relative_state1(blinkyChoice_RelativeTimerSM *me, QEvt const *e); 
QState blinkyChoice_RelativeTimerSM_finalState0(blinkyChoice_RelativeTimerSM *me, QEvt const *e); 




#endif /* BLINKYCHOICE_RELATIVETIMERSM_H_ */
