/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      relativeTimerSM
 * 
 */


 

#ifndef BLINKYCHOICE_RELATIVETIMERSM_IMPL_H
#define BLINKYCHOICE_RELATIVETIMERSM_IMPL_H

#include <qf_port.h>
#include <qassert.h>


typedef struct blinkyChoice_RelativeTimerSM_impl {
    char machineName[128];
    /** Cache of pointer to the container QActive object, for ease of access */
    QActive *active;



} blinkyChoice_RelativeTimerSM_impl;

blinkyChoice_RelativeTimerSM_impl *blinkyChoice_RelativeTimerSM_impl_constructor (blinkyChoice_RelativeTimerSM_impl *mepl);  // Default constructor
void blinkyChoice_RelativeTimerSM_impl_set_qactive (blinkyChoice_RelativeTimerSM_impl *mepl, QActive *active);

////////////////////////////////////////////
// Action and guard implementation methods
////////////////////////////////////////////

#endif  /* BLINKYCHOICE_RELATIVETIMERSM_IMPL_H */

