/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      relativeTimerSM
 * 
 */


 

#ifndef BLINKYCHOICE_RELATIVETIMERSM_STATES_H_
#define BLINKYCHOICE_RELATIVETIMERSM_STATES_H_

/**
 * Enumerate all the states that the state machine may be in at any given time.
 * An addition to the Samek pattern, state enums facilitate convenient
 * query of current state a State Machine is in at a given moment.
 */
typedef enum blinkyChoice_RelativeTimerSM_state {
    BLINKYCHOICE_RELATIVETIMERSM__TOP__, /* Top = 0 */
    BLINKYCHOICE_RELATIVETIMERSM_RELATIVE_STATE1,
    BLINKYCHOICE_RELATIVETIMERSM_FINALSTATE0,
    BLINKYCHOICE_RELATIVETIMERSM_INITSTATE,

} blinkyChoice_RelativeTimerSM_state;

#endif /* BLINKYCHOICE_RELATIVETIMERSM_STATES_H_ */
