/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      multiOrtho
 * 
 */


 

#ifndef BLINKYCHOICE_MULTIORTHO_STATES_H_
#define BLINKYCHOICE_MULTIORTHO_STATES_H_

/**
 * Enumerate all the states that the state machine may be in at any given time.
 * An addition to the Samek pattern, state enums facilitate convenient
 * query of current state a State Machine is in at a given moment.
 */
typedef enum blinkyChoice_multiOrtho_state {
    BLINKYCHOICE_MULTIORTHO__TOP__, /* Top = 0 */
    BLINKYCHOICE_MULTIORTHO_HRYOO,
    BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE0,
    BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE0_REGION1_FINALSTATE0,
    BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE0_REGION1_STATE1,
    BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE0_REGION2_FINALSTATE1,
    BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE0_REGION2_STATE2,
    BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE1,
    BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE1_REGION3_FINALSTATE2,
    BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE1_REGION3_UNNAMEDSTATE2,
    BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE1_REGION4_FINALSTATE3,
    BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE1_REGION4_UNNAMEDSTATE3,

} blinkyChoice_multiOrtho_state;

#endif /* BLINKYCHOICE_MULTIORTHO_STATES_H_ */
