/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      multiOrtho
 * 
 */


 

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <log_event.h>
#include <qf_port.h>
#include <qassert.h>
#include <assert.h>
#include <blinkyChoice_multiOrtho_impl.h>
#include <blinkyChoice_statechart_signals.h>


blinkyChoice_multiOrtho_impl *blinkyChoice_multiOrtho_impl_constructor (blinkyChoice_multiOrtho_impl *mepl) {
    strncpy(mepl->machineName, "blinkyChoice_multiOrtho", 128);
    mepl->machineName[128-1] = '\0';  // null-terminate to be sure

    // AttributeMapper_init(mepl);


    return mepl;
}

void blinkyChoice_multiOrtho_impl_set_qactive (blinkyChoice_multiOrtho_impl *mepl, QActive *active) {
    mepl->active = active;
}


////////////////////////////////////////////
// Action and guard implementation methods
////////////////////////////////////////////

