/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 */


 

#ifndef BLINKYCHOICE_STATECHART_SIGNALS_H_
#define BLINKYCHOICE_STATECHART_SIGNALS_H_

enum blinkyChoice_statechart_signals {
    /* "During" signal */
    DURING = Q_USER_SIG,

    /* User defined signals */
    BLINKYCHOICE_TURN_OFF_SIG,
    BLINKYCHOICE_TURN_ON_SIG,
    BLINKYCHOICE_WIF_HEY_SIG,

    /* Timer Event signals */
    INITSTATE_TIMER_SIG,
    ON_TIMER_SIG,
    STATE2_TIMER_SIG,

    /* State-Machine internal signals */
    _SIG_BLINKYCHOICE_HISTORYSM_COMPOSITE_OFF_COMPLETE_, 
    _SIG_BLINKYCHOICE_MODE_COMPLETE_, 
    _SIG_BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE0_COMPLETE_, 
    _SIG_BLINKYCHOICE_MULTIORTHO_UNNAMEDSTATE1_COMPLETE_, 
    _SIG_BLINKYCHOICE_ORTHOGONAL_ORTHOGONALSTATE_COMPLETE_, 
    _SIG_BLINKYCHOICE_RELATIVETIMERSM_COMPLETE_, 

    /* Maximum signal id */
    Q_BAIL_SIG = 0x7FFFFFF-1 /* Internal: terminate region/submachine */,
    MAX_SIG    = 0x7FFFFFF   /* Last possible ID! */
};

/**
 * Completion Event used to signal completion of, and thus enable exiting
 * out of, Composite and SubMachine States.  For Submachine State, event carries
 * the ID of instance -- enum value of containing substate -- that terminated.
 * If applicable, Substate event also carries exit point used.
 * 
 * Making this a C Union ensures that just enough memory is allocated to
 * contain the largest event type.
 */
typedef union {
    struct {
        QEvt super;  // C-style inheritance: QEvt is base type
        int32_t substate;   // containing substate for Submachine completion
        int32_t exitPoint;  // exitPoint used to exit Submachine, if applicable
    } completion_evt;

    QEvt base_evt;  // Mission-defined base event
} QCompletionEvt;

#endif /* BLINKYCHOICE_STATECHART_SIGNALS_H_ */
