/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      historySM
 * 
 */


 

#ifndef BLINKYCHOICE_HISTORYSM_IMPL_H
#define BLINKYCHOICE_HISTORYSM_IMPL_H

#include <qf_port.h>
#include <qassert.h>


typedef struct blinkyChoice_historySM_impl {
    char machineName[128];
    /** Cache of pointer to the container QActive object, for ease of access */
    QActive *active;

    bool hue; 



} blinkyChoice_historySM_impl;

blinkyChoice_historySM_impl *blinkyChoice_historySM_impl_constructor (blinkyChoice_historySM_impl *mepl);  // Default constructor
void blinkyChoice_historySM_impl_set_qactive (blinkyChoice_historySM_impl *mepl, QActive *active);

////////////////////////////////////////////
// Action and guard implementation methods
////////////////////////////////////////////
bool blinkyChoice_historySM_impl_hue (blinkyChoice_historySM_impl *mepl); 


#endif  /* BLINKYCHOICE_HISTORYSM_IMPL_H */

