/* 
 * This code was generated by Comodo (https://github.com/Open-MBEE/Comodo) 
 * using the QPC-C Target Platform
 *
 * - Generated Class (Comodo Module):
 *      blinkyChoice
 *
 * - Generated State Machine (Comodo Component):
 *      orthogonal
 * 
 */


 

#ifndef BLINKYCHOICE_ORTHOGONAL_IMPL_H
#define BLINKYCHOICE_ORTHOGONAL_IMPL_H

#include <qf_port.h>
#include <qassert.h>


typedef struct blinkyChoice_orthogonal_impl {
    char machineName[128];
    /** Cache of pointer to the container QActive object, for ease of access */
    QActive *active;



} blinkyChoice_orthogonal_impl;

blinkyChoice_orthogonal_impl *blinkyChoice_orthogonal_impl_constructor (blinkyChoice_orthogonal_impl *mepl);  // Default constructor
void blinkyChoice_orthogonal_impl_set_qactive (blinkyChoice_orthogonal_impl *mepl, QActive *active);

////////////////////////////////////////////
// Action and guard implementation methods
////////////////////////////////////////////
void blinkyChoice_orthogonal_impl_do_this (blinkyChoice_orthogonal_impl *mepl, int32_t arg0); 


#endif  /* BLINKYCHOICE_ORTHOGONAL_IMPL_H */

