"""
@file
@ingroup externalif2
@copyright ESO - European Southern Observatory

@defgroup externalif2
@ingroup externalif2
@brief externalif2 CII/MAL interface module.
"""

from wtools.module import declare_malicd

declare_malicd()
