"""
@file
@ingroup tools
@copyright ESO - European Southern Observatory

@defgroup scxml4py
@brief SCXML for Python
"""
from wtools.module import declare_pypackage

declare_pypackage(target='scxml4py')
