"""
@file
@ingroup hellomalif
@copyright ESO - European Southern Observatory

@defgroup hellomalif
@ingroup hellomalif
@brief hellomalif CII/MAL interface module.
"""

from wtools.module import declare_malicd

declare_malicd()
